# Generated by Django 5.0.7 on 2024-07-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_habitaciones/')),
            ],
        ),
    ]
